# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GrNbu3KHslf95kAvOHQbzTGC1TNvk74
"""

import streamlit as st
import sqlite3
from groq import Groq
import os

# ---------------------------
# PAGE SETTINGS
# ---------------------------
st.set_page_config(page_title="FoodHub AI Assistant", layout="centered")

st.title("🍔 FoodHub AI Support Assistant")
st.write("Ask about your order status, delivery ETA, or payment details.")

# ---------------------------
# LOAD GROQ CLIENT
# ---------------------------
GROQ_API_KEY = st.secrets["GROQ_API_KEY"]
client = Groq(api_key=GROQ_API_KEY)

# ---------------------------
# DATABASE CONNECTION
# ---------------------------
def run_query(sql):
    conn = sqlite3.connect("customer_orders.db")
    result = conn.execute(sql).fetchall()
    conn.close()
    return result

# ---------------------------
# PROMPT
# ---------------------------
SYSTEM_PROMPT = """
You are a SQLite expert for FoodHub.

Table: orders
Columns: order_id, cust_id, order_time, order_status, payment_status, item_in_order, price, delivery_eta

Rules:
- Return ONLY SQL
- Use LOWER() for text matching
- End with semicolon
"""

# ---------------------------
# CHAT INPUT
# ---------------------------
user_input = st.text_input("Ask your question:")

if st.button("Submit") and user_input:

    with st.spinner("Thinking..."):

        # Generate SQL using Groq
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_input}
            ]
        )

        sql = response.choices[0].message.content.strip()
        sql = sql.split(";")[0] + ";"

        st.code(sql, language="sql")

        try:
            data = run_query(sql)
            st.write("### Result")
            st.write(data)

        except Exception as e:
            st.error("Could not retrieve data.")