# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16GrNbu3KHslf95kAvOHQbzTGC1TNvk74
"""

import streamlit as st
import sqlite3

st.set_page_config(page_title="FoodHub AI Assistant", page_icon="🍔")

st.title("🍔 FoodHub AI Support Assistant")
st.caption("Ask about order status, delivery ETA, or payment details")

# ---------------------------
# SESSION STATE
# ---------------------------
if "messages" not in st.session_state:
    st.session_state.messages = []

if "cust_id" not in st.session_state:
    st.session_state.cust_id = None

# ---------------------------
# LOGIN SIMULATION
# ---------------------------
if st.session_state.cust_id is None:
    st.subheader("🔐 Customer Login (Demo Mode)")
    cust_input = st.text_input("Enter your Customer ID", "C1011")

    if st.button("Start Chat"):
        st.session_state.cust_id = cust_input.strip()
        st.rerun()

    st.stop()

# ---------------------------
# DISPLAY CHAT HISTORY
# ---------------------------
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

# ---------------------------
# USER INPUT
# ---------------------------
user_input = st.chat_input("Ask about your order...")

if user_input:
    # Store user message
    st.session_state.messages.append({"role": "user", "content": user_input})

    # ---------------------------
    # DATABASE QUERY
    # ---------------------------
    conn = sqlite3.connect("customer_orders.db")
    cursor = conn.cursor()

    query = f"""
    SELECT order_id, item_in_order, order_status, payment_status, delivery_eta
    FROM orders
    WHERE cust_id = '{st.session_state.cust_id}'
    ORDER BY order_time DESC
    LIMIT 1;
    """

    result = cursor.execute(query).fetchone()
    conn.close()

    # ---------------------------
    # RESPONSE FORMAT
    # ---------------------------
    question = user_input.lower()

    if not result:
        reply = "No recent orders found for your account."

    else:
        order_id, item, status, payment, eta = result

        # -------- INTENT DETECTION --------
        if "status" in question:
            reply = f"📍 Your order {order_id} is currently **{status}**."

        elif "eta" in question or "when" in question or "receive" in question:
            if eta:
                reply = f"⏱ Your order is expected by **{eta}**."
            else:
                reply = "⏱ Delivery time is not available yet."

        elif "payment" in question:
            reply = f"💳 Payment status: **{payment}**."

        elif "cancel" in question:
            if "delivered" in status.lower():
                reply = "❌ Sorry, the order is already delivered and cannot be cancelled."
            else:
                reply = "⚠️ Cancellation request noted. Please contact support to proceed."

        else:
            # Default full summary
            reply = f"""
📦 **Order ID:** {order_id}
🍕 **Item:** {item}
📍 **Status:** {status}
💳 **Payment:** {payment}
⏱ **ETA:** {eta if eta else 'Not available'}
"""

    # Store assistant response
    st.session_state.messages.append({"role": "assistant", "content": reply})
    st.rerun()